# Generated by Django 4.2.4 on 2023-09-04 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetmodel',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
